# #!/usr/bin/env python3
# -*- coding: utf-8 -*-
# @Time    : 2020/11/30 7:14 下午
# @Author  : 百变金刚
# @Content : test TestSuite; res_test to file
import unittest
from t02test import TestOperateCase
from HTMLTestRunner import HTMLTestRunner

def test1():
    '''
    执行所有
    :return:
    '''
    suite = unittest.TestLoader().loadTestsFromTestCase(TestOperateCase)
    unittest.TextTestRunner(verbosity=2).run(suite)

def test2():
    suite = unittest.TestSuite()

    tests = [TestOperateCase("test_add"), TestOperateCase("test_multi"), TestOperateCase("test_divide")]
    suite.addTests(tests)

    runner = unittest.TextTestRunner(verbosity=2)
    runner.run(suite)

def test2File():
    suite = unittest.TestSuite()

    tests = [TestOperateCase("test_add"), TestOperateCase("test_multi"), TestOperateCase("test_divide")]
    suite.addTests(tests)


    with open('data/res_test.result', 'w') as f:
        runner = unittest.TextTestRunner(stream=f, verbosity=2)
        runner.run(suite)

def test2Html():
    suite = unittest.TestSuite()

    tests = [TestOperateCase("test_add"), TestOperateCase("test_multi"), TestOperateCase("test_divide")]
    suite.addTests(tests)

    htmlpath = 'data/HTMLReport.html'
    with open(htmlpath, 'w') as f:
        runner = HTMLTestRunner(stream=f,
                                title='MathFunc Test Report',
                                description='generated by HTMLTestRunner.',
                                verbosity=2
                                )
        runner.run(suite)

if __name__ == '__main__':
    test2Html()
    # test2File()
    # test2()
    # test1()
'''
result of test2()
test_add (t02test.TestOperateCase) ... ok
test_multi (t02test.TestOperateCase) ... ok
test_divide (t02test.TestOperateCase) ... FAIL

======================================================================
FAIL: test_divide (t02test.TestOperateCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/baibianjingang/PycharmProjects/pyGreat-master/tools/testframe/unittestut/t02test.py", line 20, in inner
    ret = func(Operate)
  File "/Users/baibianjingang/PycharmProjects/pyGreat-master/tools/testframe/unittestut/t02test.py", line 65, in test_divide
    self.assertEqual(2, operator.divide())  # 错误case
AssertionError: 2 != 2.5

----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (failures=1)

'''
